version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:4.2
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/estate

volumes:
  mongo-data:
